language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - chmod +x gradlew